
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "/Applications/CMake.app/Contents/share/cmake-4.0/Modules/CMakeDetermineSystem.cmake:205 (message)"
      - "CMakeLists.txt:16 (project)"
    message: |
      The system is: Darwin - 25.1.0 - arm64
...
